CaseInfoPublic/Controllers/HomeController.cs
using CaseInfoPublic.Models;
using CaseInfoPublic.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CaseInfoPublic.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICaseInfoPublicRepository _caseInfoPublicRepository;

        public HomeController(ILogger<HomeController> logger, ICaseInfoPublicRepository infoPublicRepository)
        {
            _logger = logger;
            _caseInfoPublicRepository = infoPublicRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Programa()
        {
            var programas = _caseInfoPublicRepository.GetAllProgramas();

            return View("Programa", programas);
        }

        [HttpGet]
        public IActionResult EditarPrograma(ProgramaModel programa)
        {
            return View("EditarPrograma", programa);
        }

        [HttpPost]
        public IActionResult EditarProgramaPut(ProgramaModel programa)
        {
            _caseInfoPublicRepository.UpdatePrograma(programa.Codigo, programa);

            return Redirect("Programa");
        }

        [HttpGet]
        public IActionResult AdicionarPrograma(bool retomar = false) 
        {
            ViewBag.Retomar = retomar;

            return View("AdicionarPrograma", new ProgramaModel());
        }


        [HttpPost]
        public IActionResult AdicionarProgramaPost(ProgramaModel programa, bool retomar)
        {
            _caseInfoPublicRepository.CreatePrograma(programa);

            if (retomar)
                return Redirect("AdicionarIndicadorPrograma");

            return Redirect("Programa");
        }

        [HttpPost]
        public IActionResult DeletarPrograma(int codigo)
        {
            _caseInfoPublicRepository.DeletePrograma(codigo);

            return Ok();
        }

        [HttpGet]
        public IActionResult IndicadorPrograma()
        {
            var indicadoresPrograma = _caseInfoPublicRepository.GetAllIndicadoresPrograma();

            return View("IndicadorPrograma", indicadoresPrograma);
        }

        [HttpGet]
        public IActionResult EditarIndicadorPrograma(IndicadorProgramaModel indicadorPrograma)
        {
            return View("EditarIndicadorPrograma", indicadorPrograma);
        }

        [HttpPost]
        public IActionResult EditarIndicadorProgramaPut(IndicadorProgramaModel indicadorPrograma)
        {
            _caseInfoPublicRepository.UpdateIndicadorPrograma(indicadorPrograma.IdIndicador, indicadorPrograma);

            return Redirect("IndicadorPrograma");
        }

        [HttpGet]
        public IActionResult AdicionarIndicadorPrograma()
        {
            var programasSemIndicadores = GetProgramasSemIndicadores();

            if (!programasSemIndicadores.Any())
            {
                TempData["Alerta"] = "Não há programas disponíveis sem indicadores associados. Por favor, adicione um programa sem indicadores primeiro.";

                return RedirectToAction("AdicionarPrograma", new { retomar = true });
            }

            return View("AdicionarIndicadorPrograma", programasSemIndicadores);
        }

        [HttpPost]
        public IActionResult AdicionarIndicadorProgramaPost(IndicadorProgramaModel indicadorPrograma)
        {
            _caseInfoPublicRepository.CreateIndicadorPrograma(indicadorPrograma);

            return Redirect("IndicadorPrograma");
        }

        [HttpPost]
        public IActionResult DeletarIndicadorPrograma(int idIndicador)
        {
            _caseInfoPublicRepository.DeleteIndicadorPrograma(idIndicador);

            return Ok();
        }

        [HttpGet]
        public IActionResult ObjetivoPrograma()
        {
            var objetivosPrograma = _caseInfoPublicRepository.GetAllObjetivosPrograma();

            return View("ObjetivoPrograma", objetivosPrograma);
        }
        [HttpGet]
        public IActionResult EditarObjetivoPrograma(ObjetivoProgramaModel ObjetivoPrograma)
        {
            return View("EditarObjetivoPrograma", ObjetivoPrograma);
        }

        [HttpPost]
        public IActionResult EditarObjetivoProgramaPut(ObjetivoProgramaModel objetivoPrograma)
        {
            _caseInfoPublicRepository.UpdateObjetivoPrograma(objetivoPrograma.IdObjetivo, objetivoPrograma);

            return Redirect("ObjetivoPrograma");
        }

        [HttpGet]
        public IActionResult AdicionarObjetivoPrograma()
        {
            var programas = _caseInfoPublicRepository.GetAllProgramas();

            if (!programas.Any())
            {
                TempData["Alerta"] = "Não há programas cadastrados. Por favor, adicione um programa para poder prosseguir.";

                return Redirect("AdicionarPrograma");
            }

            return View("AdicionarObjetivoPrograma", programas);
        }

        [HttpPost]
        public IActionResult AdicionarObjetivoProgramaPost(ObjetivoProgramaModel objetivoPrograma)
        {
            _caseInfoPublicRepository.CreateObjetivoPrograma(objetivoPrograma.IdObjetivo, objetivoPrograma);

            return Redirect("ObjetivoPrograma");
        }

        [HttpPost]
        public IActionResult DeletarObjetivoPrograma(int idObjetivo)
        {
            _caseInfoPublicRepository.DeleteObjetivoPrograma(idObjetivo);

            return Ok();
        }

        // Método para obter programas sem indicadores associados
        private List<ProgramaModel> GetProgramasSemIndicadores()
        {
            var programas = _caseInfoPublicRepository.GetAllProgramas();
            var indicadoresProgramas = _caseInfoPublicRepository.GetAllIndicadoresPrograma();

            // Obtém uma lista de IDs de programas que estão sendo referenciados na tabela de indicadores de programa
            var programasComIndicadores = indicadoresProgramas.Select(ip => ip.IdPrograma).Distinct();

            // Obtém uma lista de programas que não estão sendo referenciados na tabela de indicadores de programa
            var programasSemIndicadores = programas.Where(p => !programasComIndicadores.Contains(p.Codigo)).ToList();

            return programasSemIndicadores;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CaseInfoPublic/Controllers/ReportController.cs
using AspNetCore.Reporting;
using CaseInfoPublic.Repositories;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Xml.Linq;

namespace CaseInfoPublic.Controllers
{
    public class ReportController : Controller
    {
        private readonly IWebHostEnvironment _iwebhostenvironment;
        private readonly ICaseInfoPublicRepository _caseInfoPublicRepository;

        public ReportController(IWebHostEnvironment iwebhostenvironment, ICaseInfoPublicRepository caseInfoPublicRepository)
        {
            _iwebhostenvironment = iwebhostenvironment;
            _caseInfoPublicRepository = caseInfoPublicRepository;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GerarRelatorioProgramas() 
        {
            var programas = _caseInfoPublicRepository.GetAllProgramas();

            // Mapear os dados para o formato necessário para o relatório
            var relatorioProgramas = programas.Select(p => new
            {
                p.Codigo,
                p.Descricao,
                p.PublicoAlvo,
                p.Tipo,
                p.ObjMilenio
            }).ToList();
            var path = $"{_iwebhostenvironment.WebRootPath}\\Reports\\ProgramasReport.rdlc";
            LocalReport localReport = new(path);
            localReport.AddDataSource("DataSetProgramas", relatorioProgramas);

            // Parâmetros opcionais para o relatório (se necessário)
                // Dictionary<string, string> parameters = new();

            var result = localReport.Execute(RenderType.Pdf, 1, null, "");

            return File(result.MainStream, "application/pdf", "RelatorioProgramas.pdf");
        }

        public IActionResult GerarRelatorioIndicadoresPrograma()
        {
            var indicadoresPrograma = _caseInfoPublicRepository.GetAllIndicadoresPrograma();

            // Mapear os dados para o formato necessário para o relatório
            var relatorioIndicadoresPrograma = indicadoresPrograma.Select(p => new
            {
                p.IdIndicador,
                p.IdPrograma,
                p.Descricao,
                p.UndMedida,
                p.IndiceApuracao,
                p.IndiceDesejado,
                p.DataApuracao
            }).ToList();

            var path = $"{_iwebhostenvironment.WebRootPath}\\Reports\\IndicadoresProgramaReport.rdlc";

            LocalReport localReport = new(path);

            // Adicionar o ReportDataSource ao LocalReport
            localReport.AddDataSource("DataSetIndicadoresPrograma", relatorioIndicadoresPrograma);

            var result = localReport.Execute(RenderType.Pdf, 1, null, "");

            return File(result.MainStream, "application/pdf", "RelatorioProgramas.pdf");
        }

        public IActionResult GerarRelatorioObjetivosPrograma()
        {
            var objetivos = _caseInfoPublicRepository.GetAllObjetivosPrograma();

            // Mapear os dados para o formato necessário para o relatório
            var relatorioObjetivosPrograma = objetivos.Select(p => new
            {
                p.IdObjetivo,
                p.IdPrograma,
                p.Descricao
            }).ToList();

            var path = $"{_iwebhostenvironment.WebRootPath}\\Reports\\ObjetivosProgramaReport.rdlc";

            LocalReport localReport = new(path);

            // Adicionar o ReportDataSource ao LocalReport
            localReport.AddDataSource("DataSetObjetivosPrograma", relatorioObjetivosPrograma);

            var result = localReport.Execute(RenderType.Pdf, 1, null, "");

            return File(result.MainStream, "application/pdf", "RelatorioObjetivosPrograma.pdf");
        }
    }
}

CaseInfoPublic/Views/Home/AdicionarIndicadorPrograma.cshtml
@model IEnumerable<ProgramaModel>
@{
    ViewData["Title"] = "Indicador Programa";
}

<div style="overflow-y: scroll; max-height: 424px; margin-bottom: 14px;">
    <form id="indicadorProgramaForm" action="/Home/AdicionarIndicadorProgramaPost" method="post">
        <div class="mb-3">
            <label for="idPrograma" class="form-label">Programa</label>
            <select class="form-select" id="idPrograma" name="idPrograma" required>
                <option selected></option>
                @foreach (var programa in Model)
                {
                    <option value="@programa.Codigo">@programa.Codigo</option>
                }
            </select>
        </div>
        <div class="mb-3">
            <label for="descricao" class="form-label">Descrição</label>
            <input type="text" class="form-control" id="descricao" name="descricao" required>
        </div>
        <div class="mb-3">
            <label for="undMedida" class="form-label">Unidade de Medida</label>
            <input type="text" class="form-control" id="undMedida" name="undMedida" required>
        </div>
        <div class="mb-3">
            <label for="indiceApuracao" class="form-label">Índice de Apuração</label>
            <input type="number" class="form-control" id="indiceApuracao" step="any" name="indiceApuracao" required>
        </div>
        <div class="mb-3">
            <label for="indiceDesejado" class="form-label">Índice Desejado</label>
            <input type="number" class="form-control" id="indiceDesejado" step="any" name="indiceDesejado" required>
        </div>
        <div class="mb-3">
            <label for="dataApuracao" class="form-label">Data de Apuração</label>
            <input type="date" class="form-control" id="dataApuracao" name="dataApuracao" required>
        </div>
    </form>
</div>
<div style="display: flex; justify-content: space-between;">
    <a class="defaultButton" href="javascript:void(0);" onclick="history.back();">Voltar</a>
    <button form="indicadorProgramaForm" type="submit" class="btn btn-primary">Salvar</button>
</div>

CaseInfoPublic/Views/Home/AdicionarObjetivoPrograma.cshtml
@model IEnumerable<ProgramaModel>
@{
    ViewData["Title"] = "Objetivo Programa";
}

<div style="overflow-y: scroll; max-height: 424px; margin-bottom: 14px;">
    <form id="objetivoProgramaForm" action="/Home/AdicionarObjetivoProgramaPost" method="post">
        <div class="mb-3">
            <label for="idPrograma" class="form-label">Programa</label>
            <select class="form-select" id="idPrograma" name="idPrograma" required>
                <option selected></option>
                @foreach (var programa in Model)
                {
                    <option value="@programa.Codigo">@programa.Codigo</option>
                }
            </select>
        </div>
        <div class="mb-3">
            <label for="descricao" class="form-label">Descrição</label>
            <input type="text" class="form-control" id="descricao" name="descricao" required>
        </div>
    </form>
</div>
<div style="display: flex; justify-content: space-between;">
    <a class="defaultButton" href="javascript:void(0);" onclick="history.back();">Voltar</a>
    <button form="objetivoProgramaForm" type="submit" class="btn btn-primary">Salvar</button>
</div>

CaseInfoPublic/Views/Home/AdicionarPrograma.cshtml
@model ProgramaModel
@{
    ViewData["Title"] = "Programa";
}

@if (TempData["Alerta"] != null)
{
    <script>
        // Exibir o alerta como um pop-up
        alert("@Html.Raw(TempData["Alerta"])");
    </script>
}

<div style="overflow-y: scroll; max-height: 424px; margin-bottom: 14px;">
    <form id="programaForm" action="/Home/AdicionarProgramaPost" method="post">
        <div class="mb-3">
            <label for="descricao" class="form-label">Descrição</label>
            <input type="text" class="form-control" id="descricao" name="descricao" required>
        </div>
        <div class="mb-3">
            <label for="publicoAlvo" class="form-label">Público-alvo</label>
            <input type="text" class="form-control" id="publicoAlvo" name="publicoAlvo" required>
        </div>
        <div class="mb-3">
            <label for="tipo" class="form-label">Tipo</label>
            <select class="form-select" id="tipo" name="tipo" required>
                <option selected></option>
                @foreach (var tipo in Model.tiposNome)
                {
                    <option value="@tipo.Key">@tipo.Value</option>
                }
            </select>
        </div>
        <div class="mb-3">
            <label for="objMilenio" class="form-label">Objetivo do Milênio</label>
            <select class="form-select" id="objMilenio" name="objMilenio" required>
                <option selected></option>
                @foreach (var objetivo in Model.objetivosNome)
                {
                    <option value="@objetivo.Key">@objetivo.Value</option>
                }
            </select>
        </div>
        <input type="hidden" id="retomar" name="retomar" value="@(ViewBag.Retomar ? "true" : "false")" />
    </form>
</div>
<div style="display: flex; justify-content: space-between;">
    <a class="defaultButton" href="javascript:void(0);" onclick="history.back();">Voltar</a>
    <button form="programaForm" type="submit" class="btn btn-primary">Salvar</button>
</div>

CaseInfoPublic/Views/Home/IndicadorPrograma.cshtml
@using Microsoft.AspNetCore.Mvc
@model IEnumerable<IndicadorProgramaModel>
@{
    ViewData["Title"] = "Indicador Programa";
}

<div style="overflow-y: scroll; max-height: 424px; margin-bottom: 14px;">
    <table class="table">
        <thead>
            <tr>
                <th style="text-align: center; align-content: center;" scope="col">Indicadores</th>
                <th style="text-align: center; align-content: center;" scope="col">Descrição</th>
                <th style="text-align: center; align-content: center;" scope="col">Programa</th>
                <th style="text-align: center; align-content: center;" scope="col">Unidade de Medida</th>
                <th style="text-align: center; align-content: center;" scope="col">Índice de Apuração</th>
                <th style="text-align: center; align-content: center;" scope="col">Índice Desejado</th>
                <th style="text-align: center; align-content: center;" scope="col">Data de Apuração</th>
                <th style="width: 10%; text-align: center; align-content: center;" scope="col"></th>
                <th style="width: 10%; text-align: center; align-content: center;" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var indicadorPrograma in Model)
            {
                <tr>
                    <th style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.IdIndicador</th>
                    <td style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.Descricao</td>
                    <td style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.IdPrograma</td>
                    <td style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.UndMedida</td>
                    <td style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.IndiceApuracao</td>
                    <td style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.IndiceDesejado</td>
                    <td style="text-align: center; align-content: center;" scope="row">@indicadorPrograma.DataApuracao.ToString("dd/MM/yyyy")</td>
                    <td style="text-align: center; align-content: center;" scope="row"><a class="defaultButton" href="@(Url.Action("EditarIndicadorPrograma", "Home", @indicadorPrograma))">Editar</a></td>
                    <td style="text-align: center; align-content: center;" scope="row">
                        <button type="button" class="deletarButton" data-bs-toggle="modal" data-bs-target="#deletarModal" data-indicadorprograma-idindicador="@indicadorPrograma.IdIndicador">
                            Deletar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="deletarModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deletarModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deletarModalLabel">Deseja continuar?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Ao confirmar, o indicador de programa selecionado será deletado.
                Deseja prosseguir?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button id="deletarButtonModal" class="deletarButton">Sim</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div style="display: flex; justify-content: space-between;">
    <a class="defaultButton" href="@(Url.Action("Index", "Home"))">Voltar</a>
    <div style="display: flex; justify-content: flex-end;">
        <a style="margin-right: 16px;" class="defaultButton" href="@Url.Action("AdicionarIndicadorPrograma", "Home")">Novo Indicador Programa</a>
        <a class="defaultButton" href="@(Url.Action("GerarRelatorioIndicadoresPrograma", "Report"))">Gerar Relatório</a>
    </div>
</div>

<script>
    $('.deletarButton').click(function () {
        var idIndicador = $(this).data('indicadorprograma-idindicador');
        $('#deletarButtonModal').data('indicadorprograma-idindicador', idIndicador);
    });

    $('#deletarButtonModal').click(function () {
        var idIndicador = $(this).data('indicadorprograma-idindicador');
        deletarIndicadorPrograma(idIndicador);
    });

    function deletarIndicadorPrograma(idIndicador) {
        $.post('@Url.Action("DeletarIndicadorPrograma", "Home")', { idIndicador: idIndicador })
            .done(function (response) {
                $('#deletarModal').modal('hide');
                window.location.reload();
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                console.error('Erro ao reprovar anúncio:', textStatus, errorThrown);
            }) 
    }
</script>

CaseInfoPublic/Views/Home/ObjetivoPrograma.cshtml
@using Microsoft.AspNetCore.Mvc
@model IEnumerable<ObjetivoProgramaModel>
@{
    ViewData["Title"] = "Objetivo Programa";
}

<div style="overflow-y: scroll; max-height: 424px; margin-bottom: 14px;">
    <table class="table">
        <thead>
            <tr>
                <th style="text-align: center; align-content: center;" scope="col">Objetivo</th>
                <th style="text-align: center; align-content: center;" scope="col">Programa</th>
                <th style="text-align: center; align-content: center;" scope="col">Descrição</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th style="width: 10%; text-align: center; align-content: center;" scope="col"></th>
                <th style="width: 10%; text-align: center; align-content: center;" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var objetivoPrograma in Model)
            {
                <tr>
                    <th style="text-align: center; align-content: center;" scope="row">@objetivoPrograma.IdObjetivo</th>
                    <td style="text-align: center; align-content: center;" scope="row">@objetivoPrograma.IdPrograma</td>
                    <td style="text-align: center; align-content: center;" scope="row">@objetivoPrograma.Descricao</td>
                    <td scope="row"></td>
                    <td scope="row"></td>
                    <td scope="row"></td>
                    <td style="text-align: center; align-content: center;" scope="row"><a class="defaultButton" href="@(Url.Action("EditarObjetivoPrograma", "Home", @objetivoPrograma))">Editar</a></td>
                    <td style="text-align: center; align-content: center;" scope="row">
                        <button type="button" class="deletarButton" data-bs-toggle="modal" data-bs-target="#deletarModal" data-objetivoprograma-idobjetivo="@objetivoPrograma.IdObjetivo">
                            Deletar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="deletarModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deletarModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deletarModalLabel">Deseja continuar?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Ao confirmar, o objetivo de programa selecionado será deletado.
                Deseja prosseguir?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button id="deletarButtonModal" class="deletarButton">Sim</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div style="display: flex; justify-content: space-between;">
    <a class="defaultButton" href="@(Url.Action("Index", "Home"))">Voltar</a>
    <div style="display: flex; justify-content: flex-end;">
        <a style="margin-right: 16px;" class="defaultButton" href="@Url.Action("AdicionarObjetivoPrograma", "Home")">Novo Objetivo Programa</a>
        <a class="defaultButton" href="@(Url.Action("GerarRelatorioObjetivosPrograma", "Report"))">Gerar Relatório</a>
    </div>
</div>

<script>
    $('.deletarButton').click(function () {
        var idObjetivo = $(this).data('objetivoprograma-idobjetivo');
        $('#deletarButtonModal').data('objetivoprograma-idobjetivo', idObjetivo);
    });

    $('#deletarButtonModal').click(function () {
        var idObjetivo = $(this).data('objetivoprograma-idobjetivo');
        deletarObjetivoPrograma(idObjetivo);
    });

    function deletarObjetivoPrograma(idObjetivo) {
        $.post('@Url.Action("DeletarObjetivoPrograma", "Home")', { idObjetivo: idObjetivo })
            .done(function (response) {
                $('#deletarModal').modal('hide');
                window.location.reload();
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                console.error('Erro ao reprovar anúncio:', textStatus, errorThrown);
            }) 
    }
</script>

CaseInfoPublic/Views/Home/Programa.cshtml
@using Microsoft.AspNetCore.Mvc
@model IEnumerable<ProgramaModel>
@{
    ViewData["Title"] = "Programa";
}

<div style="overflow-y: scroll; max-height: 424px; margin-bottom: 14px;">
    <table class="table">
        <thead>
            <tr>
                <th style="text-align: center; align-content: center;" scope="col">Programas</th>
                <th style="text-align: center; align-content: center;" scope="col">Descrição</th>
                <th style="text-align: center; align-content: center;" scope="col">Público-alvo</th>
                <th style="text-align: center; align-content: center;" scope="col">Tipo</th>
                <th style="text-align: center; align-content: center;" scope="col">Objetivo do Milênio</th>
                <th scope="col"></th>
                <th style="width: 10%; text-align: center; align-content: center;" scope="col"></th>
                <th style="width: 10%; text-align: center; align-content: center;" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var programa in Model)
            {
                //href="@(Url.Action("DeletarPrograma", "Home"))"
                <tr>
                    <th style="text-align: center; align-content: center;" scope="row">@programa.Codigo</th>
                    <td style="text-align: center; align-content: center;" scope="row">@programa.Descricao</td>
                    <td style="text-align: center; align-content: center;" scope="row">@programa.PublicoAlvo</td>
                    <td style="text-align: center; align-content: center;" scope="row">@programa.TipoNome</td>
                    <td style="text-align: center; align-content: center;" scope="row">@programa.ObjetivoNome</td>
                    <td scope="row"></td>
                    <td style="text-align: center; align-content: center;" scope="row"><a class="defaultButton" href="@(Url.Action("EditarPrograma", "Home", programa))">Editar</a></td>
                    <td style="text-align: center; align-content: center;" scope="row">
                        <button type="button" class="deletarButton" data-bs-toggle="modal" data-bs-target="#deletarModal" data-programa-codigo="@programa.Codigo">
                            Deletar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="deletarModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deletarModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deletarModalLabel">Deseja continuar?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Ao confirmar, o programa selecionado será deletado.
                Deseja prosseguir?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button id="deletarButtonModal" class="deletarButton">Sim</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div style="display: flex; justify-content: space-between;">
    <a class="defaultButton" href="@(Url.Action("Index", "Home"))">Voltar</a>
    <div style="display: flex; justify-content: flex-end;">
        <a style="margin-right: 16px;" class="defaultButton" href="@(Url.Action("AdicionarPrograma", "Home"))">Novo Programa</a>
        <a class="defaultButton" href="@(Url.Action("GerarRelatorioProgramas", "Report"))">Gerar Relatório</a>
    </div>
</div>

<script>
    $('.deletarButton').click(function () {
        var codigo = $(this).data('programa-codigo');
        $('#deletarButtonModal').data('programa-codigo', codigo);
    });

    $('#deletarButtonModal').click(function () {
        var codigo = $(this).data('programa-codigo');
        deletarPrograma(codigo);
    });

    function deletarPrograma(codigo) {
        $.post('@Url.Action("DeletarPrograma", "Home")', { codigo: codigo })
            .done(function (response) {
                $('#deletarModal').modal('hide');
                window.location.reload();
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                console.error('Erro ao reprovar anúncio:', textStatus, errorThrown);
            }) 
    }
</script>